spring:
    datasource:
      url: jdbc:mysql://localhost:3306/algacalendar?createDatabaseIfNotExist=true
      username: root
      password: root
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
